export const UI_STRINGS = {
  CONDUCTOR_HEADING: 'Conductor',
  REFRESH_BUTTON: 'Refresh',
  LIVE_FEED_EMPTY: 'No activity yet...',
  TOKEN_STAT_INPUT: 'Input',
  TOKEN_STAT_OUTPUT: 'Output',
  TOKEN_STAT_CACHE: 'Cache',
  TOKEN_STAT_COST: 'Cost',
  TOKEN_USAGE_EMPTY: 'No token data available',
  TOOL_USAGE_EMPTY: 'No tool calls recorded',
  EMPTY_STATE_HEADING: 'No Sessions Detected',
  EMPTY_STATE_DESCRIPTION:
    'Start one or more Claude Code sessions in your terminal. The dashboard will automatically discover sessions and display their activity in real time.',
  EMPTY_STATE_MONITORING: 'Monitoring ~/.claude/projects/',
  NO_SESSIONS_MATCH: 'No sessions match the current filter',
  CONTEXT_WORKING: 'Working...',
  CONTEXT_THINKING: 'Thinking...',
  CONTEXT_WAITING: 'Ready for input',
  CONTEXT_ERROR: 'Stuck \u2014 repeated errors',
  COLLAPSE_HINT: 'Esc to collapse',
  TURN_COMPLETED: 'Turn completed',
  USER_MESSAGE_FALLBACK: 'User message',
  TOOL_CALL_FALLBACK: 'Tool call',
  RESULT_ERROR: 'Error',
  RESULT_COMPLETED: 'Completed',
  RENAME_HINT: 'Double-click to rename',
  ZEN_MASCOT_TOOLTIP: 'Zen mode',
  ZEN_MASCOT_LABEL: 'Enter zen mode',
  ZEN_EXIT_LABEL: 'Exit zen mode — click anywhere',
} as const;
