export const UI_STRINGS = {
  CONDUCTOR_HEADING: 'Conductor',
  REFRESH_BUTTON: 'Refresh',
  LIVE_FEED_EMPTY: 'No activity yet...',
  TOKEN_STAT_INPUT: 'Input',
  TOKEN_STAT_OUTPUT: 'Output',
  TOKEN_STAT_CACHE: 'Cache',
  TOKEN_STAT_COST: 'Cost',
  TOKEN_USAGE_EMPTY: 'No token data available',
  TOOL_USAGE_EMPTY: 'No tool calls recorded',
  EMPTY_STATE_HEADING: 'No Sessions Detected',
  EMPTY_STATE_DESCRIPTION:
    'Start one or more Claude Code sessions in your terminal. The dashboard will automatically discover sessions and display their activity in real time.',
  EMPTY_STATE_MONITORING: 'Monitoring ~/.claude/projects/',
  NO_SESSIONS_MATCH: 'No sessions match the current filter',
  CONTEXT_WORKING: 'Working...',
  CONTEXT_THINKING: 'Thinking...',
  CONTEXT_WAITING: 'Ready for input',
  CONTEXT_ERROR: 'Stuck \u2014 repeated errors',
  CONTEXT_DONE: 'Finished',
  COLLAPSE_HINT: 'Esc to collapse',
  TURN_COMPLETED: 'Turn completed',
  USER_MESSAGE_FALLBACK: 'User message',
  TOOL_CALL_FALLBACK: 'Tool call',
  RESULT_ERROR: 'Error',
  RESULT_COMPLETED: 'Completed',
  RENAME_HINT: 'Double-click to rename',
  ZEN_MASCOT_TOOLTIP: 'Zen mode',
  ZEN_MASCOT_LABEL: 'Enter zen mode',
  ZEN_EXIT_LABEL: 'Exit zen mode — click anywhere',
  CONVERSATION_EMPTY: 'No conversation yet...',
  CONVERSATION_USER_LABEL: 'You',
  CONVERSATION_ASSISTANT_LABEL: 'Claude',
  CONVERSATION_SYSTEM_LABEL: 'System',
  TOOL_BLOCK_EXPAND: 'Click to expand',
  TOOL_BLOCK_COLLAPSE: 'Click to collapse',
  TOOL_BLOCK_ERROR: 'Error',
  TOOL_BLOCK_SUCCESS: 'OK',
  TOOL_BLOCK_PENDING: 'Running...',
  SUB_AGENT_LABEL: 'Sub-agent',
  ANALYTICS_DRAWER_TITLE: 'Analytics',
  ANALYTICS_DRAWER_TOGGLE: 'Toggle analytics',
  SUMMARY_LABEL: 'Context compressed',
  SEARCH_PLACEHOLDER: 'Search sessions...',
  SEARCH_CLEAR: 'Clear search',
  SEARCH_NO_RESULTS: 'No sessions match your search',
  DRAG_HANDLE_LABEL: 'Drag to reorder',
  DRAG_HANDLE_TOOLTIP: 'Drag to reorder sessions',
  LAYOUT_TOGGLE_TOOLTIP: 'Toggle layout orientation',
  LAYOUT_TOGGLE_LABEL: 'Toggle between vertical and horizontal layout',
  LAYOUT_ICON_VERTICAL: '\u2194',
  LAYOUT_ICON_HORIZONTAL: '\u2195',
  CHAT_INPUT_PLACEHOLDER: 'Type a response...',
  CHAT_INPUT_SEND: 'Send',
  CHAT_INPUT_SENT: 'Sent',
  CHAT_INPUT_ADOPTING: 'Opening terminal...',
  CHAT_INPUT_WAITING_PREFIX: 'Claude is asking:',
  CHAT_INPUT_ERROR: 'Failed to send',
  CHAT_INPUT_NO_TERMINAL: 'Could not send \u2014 is Claude Code installed?',
  TOOL_BLOCK_INPUT_LABEL: 'Input',
  TOOL_BLOCK_ERROR_OUTPUT_LABEL: 'Error',
  TOOL_BLOCK_OUTPUT_LABEL: 'Output',
  HEADER_STATUS_WORKING: 'working',
  HEADER_STATUS_AWAITING: 'awaiting input',
  HEADER_STATUS_ERROR: 'error',
  HEADER_COST_TOTAL: 'total',
  REFRESH_TITLE: 'Refresh sessions',
  QUESTION_OPTIONS_LABEL: 'Select an option',
  TERMINAL_VIEW_TOGGLE: 'Terminal',
  CONVERSATION_VIEW_TOGGLE: 'Chat',
  TERMINAL_TOGGLE_TOOLTIP: 'Switch between conversation and terminal view',
  LAUNCH_SESSION_BUTTON: '+',
  LAUNCH_SESSION_TOOLTIP: 'Launch a new Claude Code session',
  LAUNCH_SESSION_ERROR: 'Failed to launch session',
  NESTED_SESSION_TOOLTIP: 'Cannot launch or adopt sessions from inside Claude Code',
  CONTEXT_ENTER_PLAN_APPROVAL: 'Asking to enter plan mode',
  CONTEXT_EXIT_PLAN_APPROVAL: 'Plan ready for approval',
  CONTEXT_TOOL_APPROVAL: 'Waiting for tool approval',
  CHAT_INPUT_TOOL_APPROVAL_PREFIX: 'Pending approval:',
  CHAT_INPUT_TOOL_ALLOW: 'Allow',
  CHAT_INPUT_TOOL_ALLOW_ALWAYS: 'Allow Always',
  CHAT_INPUT_TOOL_DENY: 'Deny',
  CHAT_INPUT_PLAN_APPROVAL_PREFIX: 'Plan ready for review',
  CHAT_INPUT_PLAN_APPROVE_BUTTON: 'Approve Plan',
  CHAT_INPUT_PLAN_APPROVAL_HINT: 'Approve, or type feedback below',
  CHAT_INPUT_ENTER_PLAN_PREFIX: 'Plan mode requested',
  CHAT_INPUT_ENTER_PLAN_HINT: 'Claude is asking to switch to plan mode',
  CHAT_INPUT_ENTER_PLAN_YES: 'Yes',
  CHAT_INPUT_ENTER_PLAN_NO: 'No',
  CHAT_INPUT_OTHER_OPTION: 'Other \u2014 type a custom response below',
  TAB_SESSIONS: 'Sessions',
  TAB_HIDDEN: 'Hidden',
  CONTEXT_MENU_HIDE: 'Hide',
  CONTEXT_MENU_UNHIDE: 'Unhide',
  CONTEXT_MENU_RENAME: 'Rename',
  CONTEXT_MENU_LABEL: 'Session options',
  HIDDEN_TAB_EMPTY: 'No hidden sessions',
  /** Badge text for merged continuation sessions. Use with template: `${count} parts`. */
  CONTINUATION_BADGE: '{count} parts',
  /** Segment divider label between continuations. Use with template: `Context cleared — continuation {n} of {total}`. */
  CONTINUATION_DIVIDER: 'Context cleared — continuation {n} of {total}',
  /** Placeholder shown in TerminalView when no PTY data has been received yet. */
  TERMINAL_NO_PTY_DATA: 'Waiting for terminal output...',
  SETTINGS_DRAWER_TITLE: 'Settings',
  SETTINGS_GEAR_TOOLTIP: 'Open settings',
  SETTINGS_AUTO_HIDE_HEADING: 'Auto-hide Patterns',
  SETTINGS_AUTO_HIDE_DESCRIPTION:
    'Sessions whose name contains any of these patterns will be auto-hidden.',
  SETTINGS_AUTO_HIDE_PLACEHOLDER: 'Enter pattern...',
  SETTINGS_AUTO_HIDE_ADD: 'Add',
  SETTINGS_AUTO_HIDE_EMPTY: 'No custom patterns configured.',
  SETTINGS_CLOSE_LABEL: 'Close settings',
  /** Primary button label when in Normal launch mode. */
  LAUNCH_MODE_NORMAL: 'New Session',
  /** Primary button label when in YOLO (bypass permissions) launch mode. */
  LAUNCH_MODE_YOLO: 'Bypass Permissions',
  /** Dropdown label for Remote Control mode. */
  LAUNCH_MODE_REMOTE: 'Remote Control',
  /** Greyed-out dropdown label for Remote Control (not yet implemented). */
  LAUNCH_MODE_REMOTE_COMING_SOON: 'Remote Control (coming soon)',
  /** Micro-badge text for YOLO sessions in session cards. */
  YOLO_BADGE: 'YOLO',
  /** Tooltip/warning text shown in the YOLO dropdown item. */
  YOLO_DROPDOWN_WARNING: 'Skips all permission prompts',
  /** ARIA label for the split button chevron/dropdown trigger. */
  SPLIT_BUTTON_CHEVRON_LABEL: 'Select launch mode',
  /** ARIA label for the dropdown menu container. */
  SPLIT_BUTTON_DROPDOWN_LABEL: 'Launch mode options',
  /** Kanban board column labels */
  KANBAN_COL_PERFORMING: 'Performing',
  KANBAN_COL_AWAITING_INPUT: 'Awaiting Input',
  KANBAN_COL_NEEDS_ATTENTION: 'Needs Attention',
  KANBAN_COL_COMPLETED: 'Completed',
  /** Kanban board empty column placeholder */
  KANBAN_EMPTY_COLUMN: 'No sessions',
  /** Toggle button tooltips */
  KANBAN_TOGGLE_BOARD: 'Switch to board view',
  KANBAN_TOGGLE_LIST: 'Switch to list view',
} as const;
