/**
 * Custom Prism style object approximating VS Code Dark+ token colors.
 * Uses CSS custom properties where possible for theme awareness.
 */
import type { CSSProperties } from 'react';

export const vsCodeSyntaxTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: 'var(--vscode-editor-foreground, #d4d4d4)',
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
    lineHeight: '1.5',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    color: 'var(--vscode-editor-foreground, #d4d4d4)',
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
    lineHeight: '1.5',
    margin: '0',
    padding: '8px 10px',
    overflow: 'auto',
    borderRadius: '3px',
    background: 'rgba(0, 0, 0, 0.25)',
  },
  comment: { color: '#6a9955', fontStyle: 'italic' },
  prolog: { color: '#6a9955' },
  doctype: { color: '#6a9955' },
  cdata: { color: '#6a9955' },
  punctuation: { color: '#d4d4d4' },
  property: { color: '#9cdcfe' },
  tag: { color: '#569cd6' },
  boolean: { color: '#569cd6' },
  number: { color: '#b5cea8' },
  constant: { color: '#4fc1ff' },
  symbol: { color: '#b5cea8' },
  deleted: { color: '#ce9178' },
  selector: { color: '#d7ba7d' },
  'attr-name': { color: '#9cdcfe' },
  string: { color: '#ce9178' },
  char: { color: '#ce9178' },
  builtin: { color: '#4ec9b0' },
  inserted: { color: '#b5cea8' },
  operator: { color: '#d4d4d4' },
  entity: { color: '#4ec9b0', cursor: 'help' },
  url: { color: '#ce9178' },
  'attr-value': { color: '#ce9178' },
  keyword: { color: '#c586c0' },
  'control-flow': { color: '#c586c0' },
  function: { color: '#dcdcaa' },
  'function-variable': { color: '#dcdcaa' },
  'class-name': { color: '#4ec9b0' },
  regex: { color: '#d16969' },
  important: { color: '#569cd6', fontWeight: 'bold' },
  variable: { color: '#9cdcfe' },
  parameter: { color: '#9cdcfe' },
  interpolation: { color: '#9cdcfe' },
  'template-string': { color: '#ce9178' },
  'template-punctuation': { color: '#ce9178' },
  'script-punctuation': { color: '#d4d4d4' },
  'maybe-class-name': { color: '#4ec9b0' },
  'triple-quoted-string': { color: '#ce9178' },
  module: { color: '#4ec9b0' },
  imports: { color: '#9cdcfe' },
  exports: { color: '#9cdcfe' },
  namespace: { color: '#4ec9b0' },
  decorator: { color: '#dcdcaa' },
  'literal-property': { color: '#9cdcfe' },
};
